features:
  # When this option is enabled, the application tracks calls.
  # If no phones are configured, you can disable this function.
  #
  # Possible values:
  # True - Activates phone call tracking
  # False - Deactivates phone call tracking
  enable_phone_call_tracking: True

defaults:
  # Default value for the database name (InfluxDB)
  influx_database: 'FritzBox'
  # Number of days to retrieve call tracking in Fritz!Box
  fritzbox_phone_call_days: 1
  # Days how long phone call data should be kept in the local SQLite.
  # Note: this value has to be higher than `fritzbox_phone_call_days`
  fritzbox_phone_days_local_storage: 5

connection:
  # The username of the monitor user
  fritzbox_username:
  # The password of the monitor user
  fritzbox_password:
  # The port of the Fritz!Box.
  fritzbox_port: